//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialCapital {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SocialCapital.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        internal static string AddButtonText {
            get {
                return ResourceManager.GetString("AddButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакты из адресной книги.
        /// </summary>
        internal static string AddressBookContacts {
            get {
                return ResourceManager.GetString("AddressBookContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Импорт адресной книги.
        /// </summary>
        internal static string AddressBookMenuItemTitle {
            get {
                return ResourceManager.GetString("AddressBookMenuItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакты не синхронизированны.
        /// </summary>
        internal static string AddressBookNoSynchStatus {
            get {
                return ResourceManager.GetString("AddressBookNoSynchStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время последнего импорта контактов устройства.
        /// </summary>
        internal static string AddressBookSynchStatus {
            get {
                return ResourceManager.GetString("AddressBookSynchStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все контакты.
        /// </summary>
        internal static string AllContactsMenuItemTitle {
            get {
                return ResourceManager.GetString("AllContactsMenuItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Люди, с которыми нет необходимости, желания или возможности поддерживать общение.
        /// </summary>
        internal static string ArchiveGroupDescription {
            get {
                return ResourceManager.GetString("ArchiveGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Архив.
        /// </summary>
        internal static string ArchiveGroupName {
            get {
                return ResourceManager.GetString("ArchiveGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены что хотите удалить группу?.
        /// </summary>
        internal static string AreYouSureToDeleteGroup {
            get {
                return ResourceManager.GetString("AreYouSureToDeleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить контакты в группу.
        /// </summary>
        internal static string AssignContactsToGroup {
            get {
                return ResourceManager.GetString("AssignContactsToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Резервное копирование.
        /// </summary>
        internal static string BackupSectionHeader {
            get {
                return ResourceManager.GetString("BackupSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Базовая информация.
        /// </summary>
        internal static string BaseContactInfo {
            get {
                return ResourceManager.GetString("BaseContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Основные настройки.
        /// </summary>
        internal static string BasicSettings {
            get {
                return ResourceManager.GetString("BasicSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отменить.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Коллеги, которых ежедневно встречаете на работе.
        /// </summary>
        internal static string ColleguesGroupDescription {
            get {
                return ResourceManager.GetString("ColleguesGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Коллеги.
        /// </summary>
        internal static string ColleguesGroupName {
            get {
                return ResourceManager.GetString("ColleguesGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет истории контакта.
        /// </summary>
        internal static string CommunicationHistoryIsEmpty {
            get {
                return ResourceManager.GetString("CommunicationHistoryIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество контактов.
        /// </summary>
        internal static string ContactCountInGroup {
            get {
                return ResourceManager.GetString("ContactCountInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование контакта.
        /// </summary>
        internal static string ContactEditTitle {
            get {
                return ResourceManager.GetString("ContactEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список Контактов.
        /// </summary>
        internal static string ContactListTitle {
            get {
                return ResourceManager.GetString("ContactListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обработка контактов.
        /// </summary>
        internal static string ContactsProcessingPageTitle {
            get {
                return ResourceManager.GetString("ContactsProcessingPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на день.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        internal static string DeleteButtonText {
            get {
                return ResourceManager.GetString("DeleteButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Желаемая частота встреч.
        /// </summary>
        internal static string DesiredContactInterval {
            get {
                return ResourceManager.GetString("DesiredContactInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Готово.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Установите приложение Dropbox для создания резервной копии.
        /// </summary>
        internal static string DropboxNotLinked {
            get {
                return ResourceManager.GetString("DropboxNotLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dropbox.
        /// </summary>
        internal static string DropBoxSyncEnabled {
            get {
                return ResourceManager.GetString("DropBoxSyncEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить.
        /// </summary>
        internal static string EditContactTitle {
            get {
                return ResourceManager.GetString("EditContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        internal static string FullNameLabel {
            get {
                return ResourceManager.GetString("FullNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Распредилить.
        /// </summary>
        internal static string GroupContactCommand {
            get {
                return ResourceManager.GetString("GroupContactCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расппределено по группам:.
        /// </summary>
        internal static string GroupedContactCount {
            get {
                return ResourceManager.GetString("GroupedContactCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Группы.
        /// </summary>
        internal static string GroupPageTitle {
            get {
                return ResourceManager.GetString("GroupPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идет обновление....
        /// </summary>
        internal static string ImportStatusInProgress {
            get {
                return ResourceManager.GetString("ImportStatusInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите имя контакта.
        /// </summary>
        internal static string InputFullNamePlaceholder {
            get {
                return ResourceManager.GetString("InputFullNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название.
        /// </summary>
        internal static string InputSelectTagPlaceholder {
            get {
                return ResourceManager.GetString("InputSelectTagPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название компании.
        /// </summary>
        internal static string InputWorkplacePlaceholder {
            get {
                return ResourceManager.GetString("InputWorkplacePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите email-адрес.
        /// </summary>
        internal static string InviteToChooseEmail {
            get {
                return ResourceManager.GetString("InviteToChooseEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите номер телефона.
        /// </summary>
        internal static string InviteToChoosePhoneNumber {
            get {
                return ResourceManager.GetString("InviteToChoosePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Архив.
        /// </summary>
        internal static string IsArchiveLabel {
            get {
                return ResourceManager.GetString("IsArchiveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на История:.
        /// </summary>
        internal static string LastContactCommunicationHeader {
            get {
                return ResourceManager.GetString("LastContactCommunicationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отметить разговор.
        /// </summary>
        internal static string LogCommunicationAction {
            get {
                return ResourceManager.GetString("LogCommunicationAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Меню.
        /// </summary>
        internal static string MainMenuTitle {
            get {
                return ResourceManager.GetString("MainMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на месяц.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на никогда.
        /// </summary>
        internal static string Never {
            get {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите описание группы.
        /// </summary>
        internal static string NewGroupDescriptionEntryPlaceholder {
            get {
                return ResourceManager.GetString("NewGroupDescriptionEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название группы.
        /// </summary>
        internal static string NewGroupNameEntryPlaceholder {
            get {
                return ResourceManager.GetString("NewGroupNameEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствуют разрешения на выполнение данного действия.
        /// </summary>
        internal static string NoPermissions {
            get {
                return ResourceManager.GetString("NoPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Теги отсутствуют.
        /// </summary>
        internal static string NoTagsPlaceholder {
            get {
                return ResourceManager.GetString("NoTagsPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не обработано контактов.
        /// </summary>
        internal static string NotProcessedContactsLabel {
            get {
                return ResourceManager.GetString("NotProcessedContactsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Раз в месяц.
        /// </summary>
        internal static string OnceAMonth {
            get {
                return ResourceManager.GetString("OnceAMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Раз в три месяца.
        /// </summary>
        internal static string OnceAQuarter {
            get {
                return ResourceManager.GetString("OnceAQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Раз в год.
        /// </summary>
        internal static string OnceAYear {
            get {
                return ResourceManager.GetString("OnceAYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Телефон.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавлен.
        /// </summary>
        internal static string PhoneContactImportedStatus {
            get {
                return ResourceManager.GetString("PhoneContactImportedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвестно.
        /// </summary>
        internal static string PhoneContactUnknownStatus {
            get {
                return ResourceManager.GetString("PhoneContactUnknownStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновлён.
        /// </summary>
        internal static string PhoneContactUpdateStatus {
            get {
                return ResourceManager.GetString("PhoneContactUpdateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приоритетные.
        /// </summary>
        internal static string PriorityContactListPageTitle {
            get {
                return ResourceManager.GetString("PriorityContactListPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обработано контактов.
        /// </summary>
        internal static string ProcessedContactsLabel {
            get {
                return ResourceManager.GetString("ProcessedContactsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Близкие люди: родители, братья сёстра, бабушки, дедушки.
        /// </summary>
        internal static string RelativesGroupDescription {
            get {
                return ResourceManager.GetString("RelativesGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Родственники.
        /// </summary>
        internal static string RelativesGroupName {
            get {
                return ResourceManager.GetString("RelativesGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переименовать.
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Восстановить.
        /// </summary>
        internal static string RestoreBackup {
            get {
                return ResourceManager.GetString("RestoreBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Восстановить данные.
        /// </summary>
        internal static string RestoreBackupQuestion {
            get {
                return ResourceManager.GetString("RestoreBackupQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы уверены, что хотите восстановить резервную копию, созданную.
        /// </summary>
        internal static string RestoreBackupQuestionDetails {
            get {
                return ResourceManager.GetString("RestoreBackupQuestionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        internal static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        internal static string SettingsMenuItemTitle {
            get {
                return ResourceManager.GetString("SettingsMenuItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СМС.
        /// </summary>
        internal static string Sms {
            get {
                return ResourceManager.GetString("Sms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сводка.
        /// </summary>
        internal static string SummaryMenuItemTitle {
            get {
                return ResourceManager.GetString("SummaryMenuItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Импортировать контакты.
        /// </summary>
        internal static string SynchAddressBook {
            get {
                return ResourceManager.GetString("SynchAddressBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор тегов.
        /// </summary>
        internal static string TagSelectTitle {
            get {
                return ResourceManager.GetString("TagSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на три месяц.
        /// </summary>
        internal static string ThreeMonth {
            get {
                return ResourceManager.GetString("ThreeMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Всего контактов:.
        /// </summary>
        internal static string TotalContactCount {
            get {
                return ResourceManager.GetString("TotalContactCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общее количество контактов.
        /// </summary>
        internal static string TotalContactsCountLabel {
            get {
                return ResourceManager.GetString("TotalContactsCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Два раза в месяц.
        /// </summary>
        internal static string TwiceAMonth {
            get {
                return ResourceManager.GetString("TwiceAMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Два раза в год.
        /// </summary>
        internal static string TwiceAYear {
            get {
                return ResourceManager.GetString("TwiceAYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на два года.
        /// </summary>
        internal static string TwoYears {
            get {
                return ResourceManager.GetString("TwoYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакты без группы.
        /// </summary>
        internal static string UngroupedSectionName {
            get {
                return ResourceManager.GetString("UngroupedSectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неиспользуемые группы.
        /// </summary>
        internal static string UnusedGoupsSectionName {
            get {
                return ResourceManager.GetString("UnusedGoupsSectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакты по группам.
        /// </summary>
        internal static string UsedGoupsSectionName {
            get {
                return ResourceManager.GetString("UsedGoupsSectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интересные и полезные люди с которыми необходимо поддерживать контакт.
        /// </summary>
        internal static string UsefulGroupDescription {
            get {
                return ResourceManager.GetString("UsefulGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полезные контакты.
        /// </summary>
        internal static string UsefulGroupName {
            get {
                return ResourceManager.GetString("UsefulGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внимание.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на неделя.
        /// </summary>
        internal static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Место работы.
        /// </summary>
        internal static string WorkplaceLabel {
            get {
                return ResourceManager.GetString("WorkplaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на год.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Да.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
