#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SocialCapital.Droid.Resource", IsApplication=true)]

namespace SocialCapital.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::SocialCapital.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::SocialCapital.Droid.Resource.String.Hello;
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::SocialCapital.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::SocialCapital.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int avatar_placeholder = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_add_box_black_24dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_check_box_black_24dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_check_box_outline_blank_black_24dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_edit_black_36dp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_email_black_18dp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_email_black_36dp = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_insert_chart_black_36dp = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_insert_chart_black_48dp = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_menu_black_24dp = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_menu_black_36dp = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_people_black_36dp = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_people_black_48dp = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_phone_black_18dp = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_phone_black_36dp = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_settings_black_36dp = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_settings_black_48dp = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_sync_black_36dp = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_sync_black_48dp = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_textsms_black_18dp = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_textsms_black_36dp = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int icon = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int monoandroidsplash = 2130837526;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			// aapt resource value: 0x7f030002
			public const int app_name = 2130903042;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040000
			public const int Mono_Android_Theme_Splash = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
